# Generated by Django 3.0.7 on 2021-09-17 15:48

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalsettings',
            name='selected_project',
        ),
        migrations.RemoveField(
            model_name='personalsettings',
            name='view_only_owned',
        ),
        migrations.AddField(
            model_name='personalsettings',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settins', to='api.Project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(upload_to=api.models.upload_avatar_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desctiption',
            field=models.CharField(max_length=250),
        ),
    ]
