# Generated by Django 3.0.7 on 2021-11-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211103_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
