# Generated by Django 3.1 on 2021-09-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210918_0048'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskcategory',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='category_unique'),
        ),
    ]
