# Generated by Django 3.0.7 on 2021-11-11 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211111_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsettings',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settings', to='api.Project'),
        ),
        migrations.AlterField(
            model_name='personalsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_settings', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
