# Generated by Django 3.0.7 on 2021-11-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211111_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalsettings',
            name='project',
        ),
    ]
