# Generated by Django 3.0.7 on 2021-11-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_personalsettings_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsettings',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settings', to='api.Project'),
        ),
    ]
